### ISSUE TITLE
файл README.md принято именовать так: README.md

### ISSUE THREAD

**Issue by dimichspb** [450461/test#2]
Здесь можно указать более подробное описание проблемы

**Comment by 450461** [comment]
Какая то запутанная штукенция в целом, это единственная система такая?

**Comment by dimichspb** [comment]
Самая популярная = самая понятная

ср, 20 янв 2016 г., 11:44, 450461 <notifications@github.com>:

**Comment by dimichspb** [comment]
Issue переводится как Проблема. Когда проблема решена, ее можно закрыть Close issue

**Comment by 450461** [comment]
ок
